### ISSUE TITLE
I kid you not: three tests actually listen on port 8000.

### ISSUE THREAD

**Issue by jMyles** [hangarunderground/hendrix#87]
*    test_flask_deployment ...                                           [ERROR]
*    test_no_workers ...                                                 [ERROR]
*    test_workers ...                                                    [ERROR]

...as evinced by this traceback:

[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/justin/git/hendrix/hendrix/test/test_deploy.py", line 47, in test_flask_deployment
    deploy.start()
  File "/home/justin/git/hendrix/hendrix/deploy/base.py", line 192, in start
    self.hendrix.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/service.py", line 280, in startService
    service.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 109, in startService
    self._port = self._getPort()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 131, in _getPort
    'listen%s' % (self.method,))(*self.args, **self.kwargs)
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 492, in listenTCP
    p.startListening()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8000: [Errno 98] Address already in use.

hendrix.test.test_deploy.DeployTests.test_flask_deployment
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/justin/git/hendrix/hendrix/test/test_deploy.py", line 35, in test_no_workers
    deploy.start()
  File "/home/justin/git/hendrix/hendrix/deploy/base.py", line 192, in start
    self.hendrix.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/service.py", line 280, in startService
    service.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 109, in startService
    self._port = self._getPort()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 131, in _getPort
    'listen%s' % (self.method,))(*self.args, **self.kwargs)
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 492, in listenTCP
    p.startListening()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8000: [Errno 98] Address already in use.

hendrix.test.test_deploy.DeployTests.test_no_workers
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/justin/git/hendrix/hendrix/test/test_deploy.py", line 28, in test_workers
    deploy.start()
  File "/home/justin/git/hendrix/hendrix/deploy/base.py", line 192, in start
    self.hendrix.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/service.py", line 280, in startService
    service.startService()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 109, in startService
    self._port = self._getPort()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/application/internet.py", line 131, in _getPort
    'listen%s' % (self.method,))(*self.args, **self.kwargs)
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 492, in listenTCP
    p.startListening()
  File "/home/justin/.virtualenvs/hendrix_dev/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8000: [Errno 98] Address already in use.

hendrix.test.test_deploy.DeployTests.test_workers
-------------------------------------------------------------------------------

**Comment by JamesTFarrington** [comment]
Is there a default port we want to run tests on?

**Comment by jMyles** [comment]
I feel quite confident that we needn't run tests that listen for any actual network traffic at all.  The fact that listenTCP actually listens on a port is already tested by Twisted.

**Comment by JamesTFarrington** [comment]
Correct me if I'm wrong, but most of these tests are for HendrixDeploy. The fact that HendrixDeploy is listening on port 8000 is mostly coincidental.

**Comment by jMyles** [comment]
Sure, but if we can't test these three things (Flask compatibility, launching workers, and not launching workers) without actually listening on a TCP port, then our logic is a little too cozy.

IMO, none of these tests are correct to actually run listenTCP.  We may need to move part of the deploy logic to a lower level (or private) method and call that with the test.

**Comment by KPrasch** [comment]
Related to Issue #166.

R.I.P. @JamesTFarrington - We miss you.
